### PR TITLE
Admin, City, Event models added and made EF migrations for them

### PR DESCRIPTION
**Pull request by slapadominik**

### CODE REVIEW

**Comment by EnjoyTheNoise** [comment]
Looks fine, but what about list of questions in events?

**Comment by slapadominik** [comment]
There will be added 3 more entities: Question, Lecturer and Lecture. In the Question table there is an attribute EventId, which assigns a question to the particular event.

**Comment by EnjoyTheNoise** [comment]
Now I see, thank you for clarification.

**Comment by Nawrocka** [comment]
Looks good, commit, and I'll add 3 more.

**Comment by Nawrocka** [comment]
fuck ...I think, I did it too fast, because I'm reading about [] attribute and when we have string Description in class Event, we probably  have 25-30 range for text , it's default, that's why we should add attribute [MaxLength] or sth like that .

**Comment by Nawrocka** [comment]
datetime object can't be empty, thats why u don't need to add [required] - but maybe it's making code more clear

**Pull request merged**
